FROM quay.io/almalinuxorg/9-base:9 as repos
FROM quay.io/centos-bootc/centos-bootc:stream10 as builder

RUN rm -rf /etc/yum.repos.d/*

COPY --from=repos /etc/yum.repos.d/*.repo /etc/yum.repos.d/

COPY --from=repos /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9 /etc/pki/rpm-gpg

COPY 9/almalinux-9-workstation.yaml /usr/share/doc/bootc-base-imagectl/manifests/

RUN /usr/libexec/bootc-base-imagectl build-rootfs --reinject --manifest=almalinux-9-workstation /target-rootfs

###

FROM scratch

COPY --from=builder /target-rootfs/ /

COPY cosign.pub /usr/share/almalinux-bootc/cosign.pub

COPY system-files/ /

RUN systemd-tmpfiles --create /usr/lib/tmpfiles.d/almalinux-bootc-signing.conf

LABEL containers.bootc 1
LABEL ostree.bootable 1
LABEL org.opencontainers.image.vendor AlmaLinux OS Foundation
LABEL org.opencontainers.image.description AlmaLinux Bootable Container Image (Workstation)
RUN bootc container lint --fatal-warnings
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
